proxmox_api_url          = "http://pve-node-1:8006/api2/json"
proxmox_api_token_id     = "terraform@pve!soho"
proxmox_api_token_secret = "REPLACE_ME"

proxmox_node       = "pve"
lxc_vmid           = 210
lxc_hostname       = "soho-docker"
ostemplate         = "local:vztmpl/ubuntu-22.04-standard_22.04-1_amd64.tar.zst"
rootfs_storage     = "local-lvm"
rootfs_size        = "20G"
bridge             = "vmbr0"
lxc_ip             = "192.168.100.50/24"
gateway            = "192.168.100.1"
lxc_root_password  = "REPLACE_WITH_STRONG_PASSWORD"
ssh_public_key_path = "~/.ssh/id_ed25519.pub"
