[soho]
soho-target ansible_host=192.168.1.69 ansible_user=root ansible_ssh_private_key_file=/Users/bogdishor/.ssh/id_ed25519 ansible_ssh_common_args='-o StrictHostKeyChecking=accept-new -o UserKnownHostsFile=~/.ssh/known_hosts_soho -o GlobalKnownHostsFile=/dev/null'
